name: LambdaTest Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}

jobs:
  smartui_tests:
    name: Execute SmartUI SDK Cloud Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i @lambdatest/smartui-cli @lambdatest/playwright-driver playwright

      - name: Execute SmartUI tests
        run: npx smartui capture urls.json --config smartui-web.json

